# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rncfg2' do

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'ART',
    'Core',
    'RCTText',
    'RCTImage',
    'RCTAnimation',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'DevSupport',
    'RCTLinkingIOS',
    'RCTPushNotification',
    'CxxBridge',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTCameraRoll'
    # Add any other subspecs you want to use in your project
]

# RN dependencies
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'





  pod 'react-native-config', :path => '../node_modules/react-native-config'

end
